version: '3.8'
services:
    demo_mysql:
        container_name: demo-mysql-svr
        image: mysql:5.7
        ports:
             - 3306
        command: --init-file /docker-entrypoint-initdb.d/oai_db.sql
        volumes:
            - ./databases/oai_db-basic.sql:/docker-entrypoint-initdb.d/oai_db.sql:rw
            - ./health-scripts/mysql-healthy-check.sh:/tmp/mysql-healthy-check.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.194
    demo_oai_udr:
        container_name: demo-oai-udr
        image: oai-udr:develop
        ports:
            - 80
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=Europe/Paris
            - INSTANCE=1
            - PID_DIRECTORY=/var/run
            - UDR_NAME=OAI_UDR
            - UDR_INTERFACE_NAME_FOR_NUDR=eth0
            - UDR_INTERFACE_PORT_FOR_NUDR=80
            - UDR_INTERFACE_HTTP2_PORT_FOR_NUDR=8080
            - UDR_API_VERSION=v2
            - MYSQL_IPV4_ADDRESS=192.168.22.194
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - WAIT_MYSQL=120
            - USE_FQDN_DNS=no
            - REGISTER_NRF=no
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
        depends_on:
            - demo_mysql
            - demo_oai_nrf
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.200
        volumes:
            - ./health-scripts/udr-healthy-check.sh:/openair-udr/bin/udr-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/openair-udr/bin/udr-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_udm:
        container_name: demo-oai-udm
        image: oai-udm:develop
        ports:
            - 80
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=Europe/Paris
            - INSTANCE=1
            - PID_DIRECTORY=/var/run
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - UDM_VERSION_NB=v2
            - USE_FQDN_DNS=yes
            - UDR_IP_ADDRESS=192.168.22.200
            - UDR_PORT=80
            - UDR_VERSION_NB=v2
            - UDR_FQDN=demo_oai_udr
            - REGISTER_NRF=no
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
        depends_on:
            - demo_mysql
            - demo_oai_udr
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.201
        volumes:
            - ./health-scripts/udm-healthy-check.sh:/openair-udm/bin/udm-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/openair-udm/bin/udm-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_ausf:
        container_name: demo-oai-ausf
        image: oai-ausf:develop
        ports:
            - 80
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=Europe/Paris
            - INSTANCE_ID=1
            - PID_DIR=/var/run
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - SBI_PORT=80
            - USE_FQDN_DNS=yes
            - UDM_IP_ADDRESS=192.168.22.209
            - UDM_PORT=80
            - UDM_VERSION_NB=v2
            - UDM_FQDN=demo_oai_udm
            - REGISTER_NRF=yes
            - NRF_IPV4_ADDRESS=192.168.70.130
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
        depends_on:
            - demo_mysql
            - demo_oai_udr
            - demo_oai_udm
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.199
        volumes:
            - ./health-scripts/ausf-healthy-check.sh:/openair-ausf/bin/ausf-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/openair-ausf/bin/ausf-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_nrf:
        container_name: demo-oai-nrf
        image: oai-nrf:develop
        ports:
            - 80
            - 9090
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=Europe/Paris
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
            - NRF_INTERFACE_PORT_FOR_SBI=80
            - NRF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - NRF_API_VERSION=v1
            - INSTANCE=0
            - PID_DIRECTORY=/var/run
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.195
        volumes:
            - ./health-scripts/nrf-healthy-check.sh:/openair-nrf/bin/nrf-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/openair-nrf/bin/nrf-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_amf:
        container_name: demo-oai-amf
        image: oai-amf:develop
        ports:
             - 38412
             - 80
        cap_add:
            - NET_ADMIN
        environment:
            - INSTANCE=1
            - PID_DIRECTORY=/var/run
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0x01
            - SST_0=128
            - SD_0=128
            - SST_1=1
            - SD_1=1
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=demo_oai_smf
            - SMF_IPV4_ADDR_0=192.168.22.197
            - SMF_HTTP_VERSION_0=v1
            - SELECTED_0=true
            - SMF_INSTANCE_ID_1=2
            - SMF_FQDN_1=demo_oai_smf
            - SMF_IPV4_ADDR_1=192.168.22.197
            - SMF_HTTP_VERSION_1=v1
            - SELECTED_1=false
            - MYSQL_SERVER=demo_mysql
            - MYSQL_USER=root
            - MYSQL_PASS=linux
            - MYSQL_DB=oai_db
            - OPERATOR_KEY=63bfa50ee6523365ff14c1f45f88737d
            - NRF_IPV4_ADDRESS=192.168.22.195
            - NRF_PORT=80
            - NF_REGISTRATION=yes
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - EXTERNAL_AUSF=yes
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
            - AUSF_IPV4_ADDRESS=192.168.22.199
            - AUSF_PORT=80
            - AUSF_API_VERSION=v1
            - AUSF_FQDN=demo_oai_ausf
            - UDM_IPV4_ADDRESS=192.168.22.201
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=demo_oai_udm
        depends_on:
            - demo_mysql
            - demo_oai_nrf
            - demo_oai_udr
            - demo_oai_udm
            - demo_oai_ausf
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.196
        volumes:
            - ./health-scripts/amf-healthy-check.sh:/openair-amf/bin/amf-healthy-check.sh    
        healthcheck:
            test: /bin/bash -c "/openair-amf/bin/amf-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_smf:
        container_name: demo-oai-smf
        image: oai-smf:develop
        ports:
            - 80
            - 9090
        cap_add:
            - NET_ADMIN
        environment:
            - TZ=Europe/Paris
            - INSTANCE=1
            - PID_DIRECTORY=/var/run
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - SMF_INTERFACE_PORT_FOR_SBI=80
            - SMF_INTERFACE_HTTP2_PORT_FOR_SBI=9090
            - SMF_API_VERSION=v1
            - DEFAULT_DNS_IPV4_ADDRESS=192.168.18.129
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=4.4.4.4
            - AMF_IPV4_ADDRESS=192.168.22.196
            - AMF_PORT=80
            - AMF_API_VERSION=v1
            - AMF_FQDN=demo_oai_amf
            - UDM_IPV4_ADDRESS=127.0.0.1
            - UDM_PORT=80
            - UDM_API_VERSION=v2
            - UDM_FQDN=localhost
            - UPF_IPV4_ADDRESS=192.168.22.198
            - UPF_FQDN_0=demo_oai_upf
            - NRF_IPV4_ADDRESS=192.168.22.195
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
            - USE_LOCAL_SUBSCRIPTION_INFO=yes
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - DNN_RANGE1=12.1.1.2 - 12.1.1.128
            - DNN_RANGE0=12.2.1.2 - 12.2.1.128
            - DNN_NI1=default
            - NSSAI_SST1=128
            - NSSAI_SD1=128
            - DNN_NI2=oai
            - DNN_RANGE2=12.1.1.129 - 12.1.1.224
            - NSSAI_SST2=1
            - NSSAI_SD2=1
            - UE_MTU=1500
        depends_on:
            - demo_oai_nrf
            - demo_oai_amf
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.197
        volumes:
            - ./health-scripts/smf-healthy-check.sh:/oai-cn5g-smf/bin/smf-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/oai-cn5g-smf/bin/smf-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5
    demo_oai_upf:
        container_name: demo-oai-upf
        image: oai-spgwu-tiny:develop
        ports:
            - 2152
            - 8805
        environment:
            - TZ=Europe/Paris
            - PID_DIRECTORY=/var/run
            - SGW_INTERFACE_NAME_FOR_S1U_S12_S4_UP=eth0
            - SGW_INTERFACE_NAME_FOR_SX=eth0
            - PGW_INTERFACE_NAME_FOR_SGI=eth0
            - NETWORK_UE_NAT_OPTION=yes
            - NETWORK_UE_IP=12.1.1.0/24
            - SPGWC0_IP_ADDRESS=192.168.22.197
            - BYPASS_UL_PFCP_RULES=no
            - MCC=208
            - MNC=95
            - MNC03=095
            - TAC=40960
            - GW_ID=1
            - REALM=openairinterface.org
            - ENABLE_5G_FEATURES=yes
            - REGISTER_NRF=yes
            - USE_FQDN_NRF=yes
            - UPF_FQDN_5G=demo_oai_upf
            - NRF_IPV4_ADDRESS=192.168.22.195
            - NRF_PORT=80
            - NRF_API_VERSION=v1
            - NRF_FQDN=demo_oai_nrf
            - NSSAI_SST_0=1
            - NSSAI_SD_0=1
            - DNN_0=oai
        depends_on:
            - demo_oai_nrf
            - demo_oai_smf
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.198
        volumes:
            - ./health-scripts/upf-healthy-check.sh:/openair-spgwu-tiny/bin/upf-healthy-check.sh
        healthcheck:
            test: /bin/bash -c "/openair-spgwu-tiny/bin/upf-healthy-check.sh"
            interval: 10s
            timeout: 5s
            retries: 5

    demo_oai_ext_dn:
        image: ubuntu:bionic
        privileged: true
        container_name: demo-oai-ext-dn
        entrypoint: /bin/bash -c \
              "apt update; apt install -y iptables iproute2 iperf3 iputils-ping iperf;"\
              "iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;"\
              "ip route add 12.1.1.0/24 via 192.168.22.198 dev eth0; sleep infinity"
        depends_on:
            - demo_oai_upf
        networks:
            demo_public_net:
                ipv4_address: 192.168.22.203
 
networks:
    demo_public_net:
        name: demo-oai-public-net
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.22.192/26
        driver_opts:
            com.docker.network.bridge.name: "demo-public"
